---

name: Gatsby

on:
  push:
    branches:
      - master

concurrency:
  group: gatsby
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Check out master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: 💭 Get nvm version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
        working-directory: master

      - name: ⚙️ Setup node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: 🧶 Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        working-directory: master

      - name: 🧶 Get Yarn cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 🧶 Yarn install
        run: yarn install --pure-lockfile
        working-directory: master

      - name: 💨 ESLint
        run: yarn lint:js
        working-directory: master

      - name: ☄️ markdownlint
        run: yarn lint:md
        working-directory: master

      - name: 🥡 Getting Gatsby cache
        id: gatsby-cache-build
        uses: actions/cache@v4
        with:
          path: master/.cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: 🛎️ Check out gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: 🥡 Use gh-pages branch files as cache
        run: |
          mkdir -p public/
          mv ../gh-pages/* public/
        working-directory: master

      - name: 🧶 Yarn build
        run: yarn build
        working-directory: master

      - name: ✨ Move Gatsby output to gh-pages branch
        run: mv public/* ../gh-pages
        working-directory: master

      - name: ✔️ Commit Gatsby output changes to gh-pages branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit --allow-empty -m "${{ github.event.head_commit.message }}"
          git push
        working-directory: gh-pages

